/**
 * Default application data and starter templates.
 * Provides initial configuration values, default templates, and starter presets.
 */

import { Skill } from "../model/Skill";
import { Set as ArmorSet } from "../model/Set";
import { Weapon } from "../model/Weapon";
import { Amulet } from "../model/Amulet";
import { Options } from "../model/Options";
import { TemplateData } from "../model/Template";

export interface DefaultData {
  skills: Skill[];
  sets: ArmorSet[];
  weapons: Weapon[];
  amulets: Amulet[];
  options: Options;
  defaultTemplates: TemplateData[];
}

const DEFAULT_TEMPLATES: TemplateData[] = [
  {
    id: "default-great-sword",
    name: "Great Sword",
    skills: [
      { id: "-283334048", names: { en: "Focus", fr: "Concentration", es: "Carga veloz" }, max_points: 3, weight: 25, icon: "offense" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 20, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre", es: "Bonus de ataque" }, max_points: 5, weight: 20, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 17, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance", es: "Resentimiento" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "2083363072", names: { en: "Convert Element", fr: "Conversion élémentaire", es: "Convierte elemento" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes", es: "Ojo crítico" }, max_points: 5, weight: 9, icon: "affinity" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, max_points: 5, weight: 7, icon: "handicraft" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 9, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld", es: "Hambre de Arkveld" }, min_pieces: 2, icon: "set" },
      { id: "-62248528", names: { en: "Doshaguma's Might", fr: "Puissance du Doshaguma", es: "Poder Doshaguma" }, min_pieces: 2, icon: "set" },
      { id: "24531", names: { en: "Soul of the Dark Knight", fr: "Cristal de chevalier noir", es: "Alma del caballero oscuro" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "great-sword:87", names: { en: "Ostrak Oblivion", fr: "Ostrak oublié", es: "Ostrak olvidado" }, gear_key: "great-sword" }],
  },
  {
    id: "default-long-sword",
    name: "Long Sword",
    skills: [
      { id: "-1073401280", names: { en: "Quick Sheathe", fr: "Rengainage éclair", es: "Envainado veloz" }, max_points: 3, weight: 25, icon: "utility" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 19, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 19, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 16, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 16, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 17, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, max_points: 5, weight: 7, icon: "handicraft" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 5, weight: 5, icon: "offense" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître", es: "Toque maestro" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
    ],
    sets: [
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
    ],
    weapons: [{ id: "long-sword:91", names: { en: "Headsman's Hamus", fr: "Hamus du bourreau", es: "Hamus el Verdugo" }, gear_key: "long-sword" }],
  },
  {
    id: "default-sword-and-shield",
    name: "Sword and Shield",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive", es: "Bloqueo agresivo" }, max_points: 3, weight: 25, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 17, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 20, icon: "offense" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "144660544", names: { en: "Evade Window", fr: "Fenêtre d'invulnérabilité", es: "Intervalo de evasión" }, max_points: 3, weight: 9, icon: "utility" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître", es: "Toque maestro" }, max_points: 1, weight: 30, icon: "handicraft" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad", es: "Rebelión de Jin Dahaad" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos", es: "Fulgor de Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "sword-shield:95", names: { en: "Kyrie Verd", fr: "Kyrie Verd", es: "Kyrie Verd" }, gear_key: "sword-shield" }],
  },
  {
    id: "default-dual-blades",
    name: "Dual Blades",
    skills: [
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 25, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 23, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 21, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, max_points: 5, weight: 8, icon: "handicraft" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 17, icon: "affinity" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 15, icon: "element" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître", es: "Toque maestro" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes", es: "Ojo crítico" }, max_points: 5, weight: 10, icon: "affinity" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline", es: "Subida de adrenalina" }, max_points: 5, weight: 10, icon: "attack" },
      { id: "673822976", names: { en: "Evade Extender", fr: "Trompe-la-mort", es: "Distancia evasiva" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 10, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 5, weight: 8, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld", es: "Hambre de Arkveld" }, min_pieces: 2, icon: "set" },
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, min_pieces: 2, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "dual-blades:90", names: { en: "Eternal Cusp", fr: "Pique d'éternité", es: "Cúspide eterna" }, gear_key: "dual-blades" }],
  },
  {
    id: "default-hammer",
    name: "Hammer",
    skills: [
      { id: "-893407296", names: { en: "Slugger", fr: "Cogneur", es: "As del aturdimiento" }, max_points: 3, weight: 21, icon: "offense" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 20, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 8, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, max_points: 5, weight: 9, icon: "handicraft" },
      { id: "1470960256", names: { en: "Partbreaker", fr: "Destructeur", es: "Rompepartes" }, max_points: 3, weight: 5, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 10, icon: "element" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-283334048", names: { en: "Focus", fr: "Concentration", es: "Carga veloz" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 9, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles", es: "Antirrugidos" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "539707072", names: { en: "Rey Dau's Voltage", fr: "Tension du Rey Dau", es: "Voltaje de Rey Dau" }, min_pieces: 2, icon: "set" },
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, min_pieces: 2, icon: "set" },
      { id: "-62248528", names: { en: "Doshaguma's Might", fr: "Puissance du Doshaguma", es: "Poder Doshaguma" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "hammer:86", names: { en: "Bound Admonition", fr: "Geôle d'admonition", es: "Reprensión ligada" }, gear_key: "hammer" }],
  },
  {
    id: "default-hunting-horn",
    name: "Hunting Horn",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 10 },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 10 },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre", es: "Bonus de ataque" }, max_points: 4, weight: 10 },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline", es: "Subida de adrenalina" }, max_points: 5, weight: 7 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance", es: "Resentimiento" }, max_points: 5, weight: 7 },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 5 },
      { id: "-1237438336", names: { en: "Horn Maestro", fr: "Maestro", es: "As de la cornamusa" }, max_points: 2, weight: 10 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 10 },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, max_points: 5, weight: 5 },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3 },
      { id: "1980404096", names: { en: "Nu Udra's Mutiny", fr: "Mutinerie du Nu Udra", es: "Sublevación de Nu Udra" }, min_pieces: 2 },
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre", es: "Potencia de Odogaron Ébano" }, min_pieces: 4 },
    ],
    weapons: [{ id: "hunting-horn:86", names: { en: "Onyx Choros", fr: "Choros onyx", es: "Choros ónix" }, gear_key: "hunting-horn" }],
  },
  {
    id: "default-lance",
    name: "Lance",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive", es: "Bloqueo agresivo" }, max_points: 3, weight: 21, icon: "attack" },
      { id: "-307644128", names: { en: "Guard", fr: "Paladin", es: "Bloqueo mejorado" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "1346775424", names: { en: "Divine Blessing", fr: "Bénédiction", es: "Bendición divina" }, max_points: 3, weight: 8, icon: "defense" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes", es: "Ojo crítico" }, max_points: 3, weight: 15, icon: "affinity" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître", es: "Toque maestro" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 12, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad", es: "Rebelión de Jin Dahaad" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos", es: "Fulgor de Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "lance:85", names: { en: "Aether Pike", fr: "Lance de l'ther", es: "Pica etérea" }, gear_key: "lance" }],
  },
  {
    id: "default-gunlance",
    name: "Gunlance",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive", es: "Bloqueo agresivo" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-596764096", names: { en: "Artillery", fr: "BOUM !", es: "Artillería" }, max_points: 3, weight: 18, icon: "offense" },
      { id: "802725120", names: { en: "Load Shells", fr: "Recharge chargée", es: "Cargar arma" }, max_points: 2, weight: 15, icon: "utility" },
      { id: "-1674114176", names: { en: "Guard Up", fr: "Ultra garde", es: "Escudo" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 11, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 15, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 15, icon: "offense" },
      { id: "-307644128", names: { en: "Guard", fr: "Paladin", es: "Bloqueo mejorado" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre", es: "Bonus de ataque" }, max_points: 5, weight: 12, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles", es: "Antirrugidos" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "1346775424", names: { en: "Divine Blessing", fr: "Bénédiction", es: "Bendición divina" }, max_points: 3, weight: 10, icon: "defense" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 9, icon: "attack" },
    ],
    sets: [
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre", es: "Potencia de Odogaron Ébano" }, min_pieces: 4, icon: "set" },
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad", es: "Rebelión de Jin Dahaad" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "gunlance:84", names: { en: "Auguring Omen", fr: "Présage clairvoyant", es: "Augurio profético" }, gear_key: "gunlance" }],
  },
  {
    id: "default-switch-axe",
    name: "Switch Axe",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 10 },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 1, weight: 10 },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre", es: "Bonus de ataque" }, max_points: 4, weight: 10 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance", es: "Resentimiento" }, max_points: 2, weight: 8 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 1, weight: 10 },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente", es: "Poder latente" }, max_points: 4, weight: 10 },
      { id: "2083363072", names: { en: "Convert Element", fr: "Conversion élémentaire", es: "Convierte elemento" }, max_points: 3, weight: 10 },
      { id: "691199232", names: { en: "Power Prolonger", fr: "Puissance absolue", es: "Carga prolongada" }, max_points: 3, weight: 10 },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes", es: "Ojo crítico" }, max_points: 1, weight: 10 },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 4, weight: 10 },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3 },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2 },
      { id: "539707072", names: { en: "Rey Dau's Voltage", fr: "Tension du Rey Dau", es: "Voltaje de Rey Dau" }, min_pieces: 2 },
    ],
    weapons: [{ id: "switch-axe:80", names: { en: "Wicked Regnum", fr: "Règne malfaisant", es: "Regnum malvado" }, gear_key: "switch-axe" }],
  },
  {
    id: "default-charge-blade",
    name: "Charge Blade",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, icon: null, max_points: 4, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, icon: null, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, icon: null, max_points: 5, weight: 10 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance", es: "Resentimiento" }, icon: null, max_points: 2, weight: 8 },
      { id: "802725120", names: { en: "Load Shells", fr: "Recharge chargée", es: "Cargar arma" }, icon: null, max_points: 2, weight: 10 },
      { id: "-283334048", names: { en: "Focus", fr: "Concentration", es: "Carga veloz" }, icon: null, max_points: 3, weight: 10 },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, icon: null, max_points: 4, weight: 10 },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union", es: "Coalescencia" }, icon: null, max_points: 3, weight: 10 },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire", es: "Artesanía" }, icon: null, max_points: 2, weight: 10 },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline", es: "Subida de adrenalina" }, icon: null, max_points: 2, weight: 10 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, icon: null, max_points: 3, weight: 10 },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles", es: "Antirrugidos" }, icon: null, max_points: 2, weight: 10 },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, icon: null, min_pieces: 4 },
      { id: "-403054144", names: { en: "Mizutsune's Prowess", fr: "Prouesse du Mizutsune", es: "Poder de Mizutsune" }, icon: null, min_pieces: 2 },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos", es: "Fulgor de Rathalos" }, icon: null, min_pieces: 2 },
    ],
    weapons: [{ id: "charge-blade:85", names: { en: "Promised Abyss", fr: "Abîme promis", es: "Abismo prometido" }, gear_key: "charge-blade" }],
  },
  {
    id: "default-insect-glaive",
    name: "Insect Glaive",
    skills: [
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur", es: "Desuello" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 21, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque", es: "Venganza" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre", es: "Bonus de ataque" }, max_points: 5, weight: 16, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 13, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker", es: "Bonus críticos" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 9, icon: "attack" },
      { id: "402237312", names: { en: "Airborne", fr: "Mort venue d'en haut", es: "Bonus ataque en salto" }, max_points: 1, weight: 30, icon: "offense" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles", es: "Antirrugidos" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier", es: "Ingesta rápida" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur", es: "Alma del amo" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld", es: "Hambre de Arkveld" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "insect-glaive:86", names: { en: "Limbo Llor", fr: "Larmes des limbes", es: "Limbo Llor" }, gear_key: "insect-glaive" }],
  },
  {
    id: "default-light-bowgun",
    name: "Light Bowgun",
    skills: [
      { id: "-1507579776", names: { en: "Rapid Fire Up", fr: "Tir super rapide", es: "Andanada rápida" }, max_points: 1, weight: 25, icon: "ranged" },
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique", es: "Balística" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1711950720", names: { en: "Opening Shot", fr: "Premier tir", es: "Primer disparo" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union", es: "Coalescencia" }, max_points: 3, weight: 12, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 14, icon: "element" },
      { id: "313598432", names: { en: "Critical Element", fr: "Rage élémentaire", es: "Elemento crítico" }, max_points: 3, weight: 14, icon: "element" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles", es: "Antirrugidos" }, max_points: 3, weight: 9, icon: "utility" },
      { id: "144660544", names: { en: "Evade Window", fr: "Fenêtre d'invulnérabilité", es: "Intervalo de evasión" }, max_points: 3, weight: 9, icon: "utility" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, min_pieces: 4, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "light-bowgun:86", names: { en: "Bethorned Agony", fr: "Agonie épineuse", es: "Agonía espinada" }, gear_key: "light-bowgun" }],
  },
  {
    id: "default-heavy-bowgun",
    name: "Heavy Bowgun",
    skills: [
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique", es: "Balística" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1711950720", names: { en: "Opening Shot", fr: "Premier tir", es: "Primer disparo" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union", es: "Coalescencia" }, max_points: 3, weight: 12, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus", es: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 14, icon: "element" },
      { id: "313598432", names: { en: "Critical Element", fr: "Rage élémentaire", es: "Elemento crítico" }, max_points: 3, weight: 14, icon: "element" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme", es: "Poder máximo" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "-596764096", names: { en: "Artillery", fr: "BOUM !" }, max_points: 3, weight: 15, icon: "offense" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline", es: "Subida de adrenalina" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier", es: "Ingesta rápida" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, min_pieces: 4, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala", es: "Tiranía de Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "heavy-bowgun:80", names: { en: "Trembling Hels", fr: "Tremblement infernal", es: "Hels temblorosa" }, gear_key: "heavy-bowgun" }],
  },
  {
    id: "default-bow",
    name: "Bow",
    skills: [
      { id: "-1689391744", names: { en: "Constitution", fr: "Athlète", es: "Constitución" }, max_points: 5, weight: 25, icon: "stamina" },
      { id: "-315492576", names: { en: "Stamina Surge", fr: "Métabolisme", es: "Aguante" }, max_points: 3, weight: 20, icon: "stamina" },
      { id: "-1475134080", names: { en: "Charge Master", fr: "Maître de la charge", es: "Maestro de cargas" }, max_points: 3, weight: 20, icon: "element" },
      { id: "1613139840", names: { en: "Tetrad Shot", fr: "Quatrième tir", es: "Disparo tétrada" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique", es: "Balística" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta", es: "Ráfaga" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort", es: "Punto débil" }, max_points: 5, weight: 20, icon: "attack" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane", es: "Ataque de fuego" }, max_points: 3, weight: 15, icon: "element" },
      { id: "-2123993856", names: { en: "Spread/Power Shots", fr: "Désigné pour mourir", es: "Disparo abanico/potente" }, max_points: 1, weight: 30, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité", es: "Instigación" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale", es: "Plena forma" }, max_points: 5, weight: 13, icon: "attack" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier", es: "Ingesta rápida" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline", es: "Subida de adrenalina" }, max_points: 5, weight: 9, icon: "attack" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse", es: "Gogmapocalipsis" }, min_pieces: 4, icon: "set" },
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre", es: "Potencia de Odogaron Ébano" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos", es: "Fulgor de Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "bow:91", names: { en: "Calamitous Angel", fr: "Ange de calamité", es: "Ángel calamitoso" }, gear_key: "bow" }],
  },
];

export const DEFAULT_DATA: DefaultData = {
  skills: DEFAULT_TEMPLATES[1].skills,
  sets: DEFAULT_TEMPLATES[1].sets,
  weapons: DEFAULT_TEMPLATES[1].weapons,
  amulets: [],
  options: { include_all_amulets: true, transcend: true, include_gog_sets: true },
  defaultTemplates: DEFAULT_TEMPLATES
};
