/**
 * Default application data and starter templates.
 * Provides initial configuration values, default templates, and starter presets.
 */

import { Skill } from "../model/Skill";
import { Set as ArmorSet } from "../model/Set";
import { Weapon } from "../model/Weapon";
import { Amulet } from "../model/Amulet";
import { Options } from "../model/Options";
import { TemplateData } from "../model/Template";

export interface DefaultData {
  skills: Skill[];
  sets: ArmorSet[];
  weapons: Weapon[];
  amulets: Amulet[];
  options: Options;
  defaultTemplates: TemplateData[];
}

const SKILL_ICON_BY_ID: Record<string, Skill["icon"]> = {
  "-1073401280": "utility",
  "-1237438336": "offense",
  "-1475134080": "element",
  "-1507579776": "ranged",
  "-160562336": "ranged",
  "-1607763456": "affinity",
  "-1674114176": "utility",
  "-1689391744": "stamina",
  "-1700743296": "offense",
  "-181127504": "attack",
  "-283334048": "offense",
  "-307644128": "utility",
  "-315492576": "stamina",
  "-397570464": "attack",
  "-420608864": "ranged",
  "-562534336": "element",
  "-596764096": "offense",
  "-856322816": "offense",
  "-893407296": "offense",
  // Set / group bonus IDs used by defaults/templates.
  "722735744": "set",
  "-1768553344": "set",
  "1484575872": "group",
  "-3666104": "set",
  "-215826112": "set",
  "-418246240": "set",
  "539707072": "set",
  "-403054144": "set",
  "-964369920": "set",
  "-62248528": "set",
  "24531": "set",
  "5590": "set",
  "1980404096": "set",
  "918165056": "set",
  "1": "attack",
  "1050520384": "handicraft",
  "1160639488": "handicraft",
  "1174975744": "attack",
  "1346775424": "defense",
  "1359821952": "attack",
  "1389859584": "handicraft",
  "144660544": "utility",
  "1470960256": "offense",
  "1613139840": "ranged",
  "1711950720": "ranged",
  "1763191040": "offense",
  "1865909632": "offense",
  "2083363072": "attack",
  "2106877312": "attack",
  "280489184": "attack",
  "313598432": "element",
  "402237312": "offense",
  "565867136": "offense",
  "632127488": "attack",
  "673822976": "utility",
  "691199232": "offense",
  "802725120": "utility",
  "-1662120192": "offense",
  "-2096489472": "affinity",
};

const withSkillIcons = (skills: Skill[] | ArmorSet[]): Skill[] | ArmorSet[] => skills.map((skill) => ({ ...skill, icon: skill.icon ?? SKILL_ICON_BY_ID[skill.id] ?? null }));

const withTemplateSkillIcons = (templates: TemplateData[]): TemplateData[] => templates.map((template) => ({ ...template, skills: withSkillIcons(template.skills), sets: withSkillIcons(template.sets) }));

const DEFAULT_TEMPLATES: TemplateData[] = [
  {
    id: "default-great-sword",
    name: "Great Sword",
    skills: [
      { id: "-283334048", names: { en: "Focus", fr: "Concentration" }, max_points: 3, weight: 25, icon: "offense" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 20, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre" }, max_points: 5, weight: 20, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 17, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "2083363072", names: { en: "Convert Element", fr: "Conversion élémentaire" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes" }, max_points: 5, weight: 9, icon: "affinity" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, max_points: 5, weight: 7, icon: "handicraft" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 9, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld" }, min_pieces: 2, icon: "set" },
      { id: "-62248528", names: { en: "Doshaguma's Might", fr: "Puissance du Doshaguma" }, min_pieces: 2, icon: "set" },
      { id: "24531", names: { en: "Soul of the Dark Knight", fr: "Cristal de chevalier noir" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "great-sword:87", names: { en: "Ostrak Oblivion", fr: "Ostrak oublié" }, gear_key: "great-sword" }],
  },
  {
    id: "default-long-sword",
    name: "Long Sword",
    skills: [
      { id: "-1073401280", names: { en: "Quick Sheathe", fr: "Rengainage éclair" }, max_points: 3, weight: 25, icon: "utility" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 19, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 19, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 16, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 16, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 17, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, max_points: 5, weight: 7, icon: "handicraft" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 5, weight: 5, icon: "offense" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
    ],
    sets: [
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 2, icon: "group" },
    ],
    weapons: [{ id: "long-sword:91", names: { en: "Headsman's Hamus", fr: "Hamus du bourreau" }, gear_key: "long-sword" }],
  },
  {
    id: "default-sword-and-shield",
    name: "Sword and Shield",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive" }, max_points: 3, weight: 25, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 17, icon: "affinity" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 20, icon: "offense" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "144660544", names: { en: "Evade Window", fr: "Fenêtre d'invulnérabilité" }, max_points: 3, weight: 9, icon: "utility" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître" }, max_points: 1, weight: 30, icon: "handicraft" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "sword-shield:95", names: { en: "Kyrie Verd", fr: "Kyrie Verd" }, gear_key: "sword-shield" }],
  },
  {
    id: "default-dual-blades",
    name: "Dual Blades",
    skills: [
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 25, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 23, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 21, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, max_points: 5, weight: 8, icon: "handicraft" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 17, icon: "affinity" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 15, icon: "element" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes" }, max_points: 5, weight: 10, icon: "affinity" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline" }, max_points: 5, weight: 10, icon: "attack" },
      { id: "673822976", names: { en: "Evade Extender", fr: "Trompe-la-mort" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 10, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 5, weight: 8, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld" }, min_pieces: 2, icon: "set" },
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, min_pieces: 2, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "dual-blades:90", names: { en: "Eternal Cusp", fr: "Pique d'éternité" }, gear_key: "dual-blades" }],
  },
  {
    id: "default-hammer",
    name: "Hammer",
    skills: [
      { id: "-893407296", names: { en: "Slugger", fr: "Cogneur" }, max_points: 3, weight: 21, icon: "offense" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 20, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 8, icon: "attack" },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, max_points: 5, weight: 9, icon: "handicraft" },
      { id: "1470960256", names: { en: "Partbreaker", fr: "Destructeur" }, max_points: 3, weight: 5, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 10, icon: "element" },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-283334048", names: { en: "Focus", fr: "Concentration" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 9, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "539707072", names: { en: "Rey Dau's Voltage", fr: "Tension du Rey Dau" }, min_pieces: 2, icon: "set" },
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, min_pieces: 2, icon: "set" },
      { id: "-62248528", names: { en: "Doshaguma's Might", fr: "Puissance du Doshaguma" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "hammer:86", names: { en: "Bound Admonition", fr: "Geôle d'admonition" }, gear_key: "hammer" }],
  },
  {
    id: "default-hunting-horn",
    name: "Hunting Horn",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 10 },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 10 },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre" }, max_points: 4, weight: 10 },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline" }, max_points: 5, weight: 7 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance" }, max_points: 5, weight: 7 },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 5 },
      { id: "-1237438336", names: { en: "Horn Maestro", fr: "Maestro" }, max_points: 2, weight: 10 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 10 },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, max_points: 5, weight: 5 },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3 },
      { id: "1980404096", names: { en: "Nu Udra's Mutiny", fr: "Mutinerie du Nu Udra" }, min_pieces: 2 },
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre" }, min_pieces: 4 },
    ],
    weapons: [{ id: "hunting-horn:86", names: { en: "Onyx Choros", fr: "Choros onyx" }, gear_key: "hunting-horn" }],
  },
  {
    id: "default-lance",
    name: "Lance",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive" }, max_points: 3, weight: 21, icon: "attack" },
      { id: "-307644128", names: { en: "Guard", fr: "Paladin" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "1346775424", names: { en: "Divine Blessing", fr: "Bénédiction" }, max_points: 3, weight: 8, icon: "defense" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 10, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes" }, max_points: 3, weight: 15, icon: "affinity" },
      { id: "1389859584", names: { en: "Master's Touch", fr: "Main de maître" }, max_points: 1, weight: 30, icon: "handicraft" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 12, icon: "offense" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "lance:85", names: { en: "Aether Pike", fr: "Lance de l'ther" }, gear_key: "lance" }],
  },
  {
    id: "default-gunlance",
    name: "Gunlance",
    skills: [
      { id: "-181127504", names: { en: "Offensive Guard", fr: "Garde offensive" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-596764096", names: { en: "Artillery", fr: "BOUM !" }, max_points: 3, weight: 18, icon: "offense" },
      { id: "802725120", names: { en: "Load Shells", fr: "Recharge chargée" }, max_points: 2, weight: 15, icon: "utility" },
      { id: "-1674114176", names: { en: "Guard Up", fr: "Ultra garde" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 11, icon: "attack" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 15, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 15, icon: "offense" },
      { id: "-307644128", names: { en: "Guard", fr: "Paladin" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre" }, max_points: 5, weight: 12, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "1346775424", names: { en: "Divine Blessing", fr: "Bénédiction" }, max_points: 3, weight: 10, icon: "defense" },
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 9, icon: "attack" },
    ],
    sets: [
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre" }, min_pieces: 4, icon: "set" },
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "-215826112", names: { en: "Jin Dahaad's Revolt", fr: "Révolte du Jin Dahaad" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "gunlance:84", names: { en: "Auguring Omen", fr: "Présage clairvoyant" }, gear_key: "gunlance" }],
  },
  {
    id: "default-switch-axe",
    name: "Switch Axe",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 10 },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 1, weight: 10 },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre" }, max_points: 4, weight: 10 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance" }, max_points: 2, weight: 8 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 1, weight: 10 },
      { id: "1763191040", names: { en: "Latent Power", fr: "Force latente" }, max_points: 4, weight: 10 },
      { id: "2083363072", names: { en: "Convert Element", fr: "Conversion élémentaire" }, max_points: 3, weight: 10 },
      { id: "691199232", names: { en: "Power Prolonger", fr: "Puissance absolue" }, max_points: 3, weight: 10 },
      { id: "-2096489472", names: { en: "Critical Eye", fr: "Maître d'armes" }, max_points: 1, weight: 10 },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 4, weight: 10 },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 2 },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2 },
      { id: "539707072", names: { en: "Rey Dau's Voltage", fr: "Tension du Rey Dau" }, min_pieces: 2 },
    ],
    weapons: [{ id: "switch-axe:80", names: { en: "Wicked Regnum", fr: "Règne malfaisant" }, gear_key: "switch-axe" }],
  },
  {
    id: "default-charge-blade",
    name: "Charge Blade",
    skills: [
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, icon: null, max_points: 4, weight: 10 },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, icon: null, max_points: 3, weight: 10 },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, icon: null, max_points: 5, weight: 10 },
      { id: "1359821952", names: { en: "Resentment", fr: "Vengeance" }, icon: null, max_points: 2, weight: 8 },
      { id: "802725120", names: { en: "Load Shells", fr: "Recharge chargée" }, icon: null, max_points: 2, weight: 10 },
      { id: "-283334048", names: { en: "Focus", fr: "Concentration" }, icon: null, max_points: 3, weight: 10 },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, icon: null, max_points: 4, weight: 10 },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union" }, icon: null, max_points: 3, weight: 10 },
      { id: "1160639488", names: { en: "Handicraft", fr: "Savoir-faire" }, icon: null, max_points: 2, weight: 10 },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline" }, icon: null, max_points: 2, weight: 10 },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, icon: null, max_points: 3, weight: 10 },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles" }, icon: null, max_points: 2, weight: 10 },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, icon: null, min_pieces: 4 },
      { id: "-403054144", names: { en: "Mizutsune's Prowess", fr: "Prouesse du Mizutsune" }, icon: null, min_pieces: 2 },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos" }, icon: null, min_pieces: 2 },
    ],
    weapons: [{ id: "charge-blade:85", names: { en: "Promised Abyss", fr: "Abîme promis" }, gear_key: "charge-blade" }],
  },
  {
    id: "default-insect-glaive",
    name: "Insect Glaive",
    skills: [
      { id: "-856322816", names: { en: "Flayer", fr: "Écorcheur" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 21, icon: "offense" },
      { id: "280489184", names: { en: "Counterstrike", fr: "Contre-attaque" }, max_points: 3, weight: 19, icon: "attack" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 17, icon: "attack" },
      { id: "1", names: { en: "Attack Boost", fr: "Machine de guerre" }, max_points: 5, weight: 16, icon: "attack" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 13, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 8, icon: "offense" },
      { id: "-1607763456", names: { en: "Critical Boost", fr: "Berserker" }, max_points: 5, weight: 15, icon: "affinity" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 9, icon: "attack" },
      { id: "402237312", names: { en: "Airborne", fr: "Mort venue d'en haut" }, max_points: 1, weight: 30, icon: "offense" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles" }, max_points: 3, weight: 8, icon: "utility" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "1484575872", names: { en: "Lord's Soul", fr: "Âme du seigneur" }, min_pieces: 3, icon: "group" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
      { id: "-964369920", names: { en: "Arkveld's Hunger", fr: "Appétit de l'Arkveld" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "insect-glaive:86", names: { en: "Limbo Llor", fr: "Larmes des limbes" }, gear_key: "insect-glaive" }],
  },
  {
    id: "default-light-bowgun",
    name: "Light Bowgun",
    skills: [
      { id: "-1507579776", names: { en: "Rapid Fire Up", fr: "Tir super rapide" }, max_points: 1, weight: 25, icon: "ranged" },
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1711950720", names: { en: "Opening Shot", fr: "Premier tir" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union" }, max_points: 3, weight: 12, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 14, icon: "element" },
      { id: "313598432", names: { en: "Critical Element", fr: "Rage élémentaire" }, max_points: 3, weight: 14, icon: "element" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "192746944", names: { en: "Earplugs", fr: "Bouchon d'oreilles" }, max_points: 3, weight: 9, icon: "utility" },
      { id: "144660544", names: { en: "Evade Window", fr: "Fenêtre d'invulnérabilité" }, max_points: 3, weight: 9, icon: "utility" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, min_pieces: 4, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "light-bowgun:86", names: { en: "Bethorned Agony", fr: "Agonie épineuse" }, gear_key: "light-bowgun" }],
  },
  {
    id: "default-heavy-bowgun",
    name: "Heavy Bowgun",
    skills: [
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1711950720", names: { en: "Opening Shot", fr: "Premier tir" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 9, icon: "offense" },
      { id: "-1700743296", names: { en: "Coalescence", fr: "Union" }, max_points: 3, weight: 12, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 15, icon: "attack" },
      { id: "-1662120192", names: { en: "Antivirus", fr: "Antivirus" }, max_points: 3, weight: 10, icon: "offense" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 14, icon: "element" },
      { id: "313598432", names: { en: "Critical Element", fr: "Rage élémentaire" }, max_points: 3, weight: 14, icon: "element" },
      { id: "632127488", names: { en: "Maximum Might", fr: "Corps et âme" }, max_points: 3, weight: 12, icon: "attack" },
      { id: "-596764096", names: { en: "Artillery", fr: "BOUM !" }, max_points: 3, weight: 15, icon: "offense" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline" }, max_points: 5, weight: 8, icon: "attack" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier" }, max_points: 3, weight: 10, icon: "utility" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, min_pieces: 4, icon: "set" },
      { id: "722735744", names: { en: "Gore Magala's Tyranny", fr: "Tyrannie du Gore Magala" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "heavy-bowgun:80", names: { en: "Trembling Hels", fr: "Tremblement infernal" }, gear_key: "heavy-bowgun" }],
  },
  {
    id: "default-bow",
    name: "Bow",
    skills: [
      { id: "-1689391744", names: { en: "Constitution", fr: "Athlète" }, max_points: 5, weight: 25, icon: "stamina" },
      { id: "-315492576", names: { en: "Stamina Surge", fr: "Métabolisme" }, max_points: 3, weight: 20, icon: "stamina" },
      { id: "-1475134080", names: { en: "Charge Master", fr: "Maître de la charge" }, max_points: 3, weight: 20, icon: "element" },
      { id: "1613139840", names: { en: "Tetrad Shot", fr: "Quatrième tir" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "-420608864", names: { en: "Ballistics", fr: "Balistique" }, max_points: 3, weight: 8, icon: "ranged" },
      { id: "565867136", names: { en: "Burst", fr: "Vendetta" }, max_points: 5, weight: 12, icon: "offense" },
      { id: "-397570464", names: { en: "Weakness Exploit", fr: "Mise à mort" }, max_points: 5, weight: 20, icon: "attack" },
      { id: "-562534336", names: { en: "Fire Attack", fr: "Pyromane" }, max_points: 3, weight: 15, icon: "element" },
      { id: "-2123993856", names: { en: "Spread/Power Shots", fr: "Désigné pour mourir" }, max_points: 1, weight: 30, icon: "ranged" },
      { id: "1865909632", names: { en: "Agitator", fr: "Témérité" }, max_points: 5, weight: 13, icon: "offense" },
      { id: "2106877312", names: { en: "Peak Performance", fr: "Performance optimale" }, max_points: 5, weight: 13, icon: "attack" },
      { id: "634068352", names: { en: "Speed Eating", fr: "Carnassier" }, max_points: 3, weight: 10, icon: "utility" },
      { id: "1174975744", names: { en: "Adrenaline Rush", fr: "Poussée d'adrénaline" }, max_points: 5, weight: 9, icon: "attack" },
    ],
    sets: [
      { id: "5590", names: { en: "Gogmapocalypse", fr: "Gogmapocalypse" }, min_pieces: 4, icon: "set" },
      { id: "918165056", names: { en: "Ebony Odogaron's Power", fr: "Pouvoir de l'Odogaron désastre" }, min_pieces: 2, icon: "set" },
      { id: "-3666104", names: { en: "Rathalos's Flare", fr: "Éclat du Rathalos" }, min_pieces: 2, icon: "set" },
    ],
    weapons: [{ id: "bow:91", names: { en: "Calamitous Angel", fr: "Ange de calamité" }, gear_key: "bow" }],
  },
];

export const DEFAULT_DATA: DefaultData = { skills: withSkillIcons(DEFAULT_TEMPLATES[1].skills), sets: withSkillIcons(DEFAULT_TEMPLATES[1].sets), weapons: DEFAULT_TEMPLATES[1].weapons, amulets: [], options: { include_all_amulets: true, transcend: true, include_gog_sets: true }, defaultTemplates: withTemplateSkillIcons(DEFAULT_TEMPLATES) };
